### ISSUE TITLE
capstone error

### ISSUE THREAD

**Issue by papsire** [secretsquirrel/fido#2]
root@php:/opt/fido# cat fredtest.bin | ./fido.py -p LLAGPA  >test.bin
Traceback (most recent call last):
  File "./fido.py", line 5, in <module>
    from capstone import *
ImportError: No module named 'capstone'

i have capstone installed

**Comment by secretsquirrel** [comment]
It's python3, you will need to install the python3 bindings.

**Comment by papsire** [comment]
i still have same issue.am running it on Kali

**Comment by hawaii67** [comment]
use this:
pip3 install capstone
